# No longer explicitly listing all files
SRC_DIR=src
SRCS := $(shell find $(SRC_DIR) -name '*.cpp')
SRCS := $(filter-out $(SRC_DIR)/tests/%, $(SRCS))

TARGET_DIR=build/out
OBJ_DIR=build/obj
OBJS=$(SRCS:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%.o)
DEBUG_OBJS=$(SRCS:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%-debug.o)

TARGET=$(TARGET_DIR)/poc
DEBUG_TARGET=$(TARGET_DIR)/poc-debug

CXX=g++
DEPFLAGS=-MMD -MP
CXXFLAGS=-I$(SRC_DIR) -std=c++23
LIBS=-lgmp -lgmpxx -lcrypto
DEBUG_DEFS=

#ASN1_DEBUG // print debugging information while parsing ASN1 objects
ifeq ($(ASN1),1)
	DEBUG_DEFS += -DASN1_DEBUG
endif
#KDF_DEBUG // print debugging information while deriving keys
ifeq ($(KDF),1)
	DEBUG_DEFS += -DKDF_DEBUG
endif
#AES_DEBUG // print debugging information while performing AES encryption/decryption
ifeq ($(AES),1)
	DEBUG_DEFS += -DAES_DEBUG
endif
#RSA_DEBUG // print debugging information while parsing RSA keys
ifeq ($(RSA),1)
	DEBUG_DEFS += -DRSA_DEBUG
endif
#SECURE_FREE_DEBUG // print debugging information when secure_free is called
ifeq ($(SECURE_FREE),1)
	DEBUG_DEFS += -DSECURE_FREE_DEBUG
endif
#OPENSSL_DEBUG // print debugging information when fetching/clearing OpenSSL algorithms
ifeq ($(OPENSSL),1)
	DEBUG_DEFS += -DOPENSSL_DEBUG
endif
#GMP_DEBUG // print debugging information on total GMP memory allocation
ifeq ($(GMP),1)
	DEBUG_DEFS += -DGMP_DEBUG
endif
#SKIP_INPUT_DEBUG // skip manual information input and use some defaults instead
ifeq ($(SKIP_INPUT),1)
	DEBUG_DEFS += -DSKIP_INPUT_DEBUG
endif

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(DEPFLAGS) -c $< -o $@

$(OBJ_DIR)/%-debug.o: $(SRC_DIR)/%.cpp
	mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(DEPFLAGS) $(DEBUG_DEFS) -g -c $< -o $@

all: $(TARGET)

$(TARGET): $(OBJS)
	mkdir -p $(TARGET_DIR)
	$(CXX) $(CXXFLAGS) $(OBJS) $(LIBS) -O3 -DNDEBUG -o $@

debug: $(DEBUG_TARGET)

$(DEBUG_TARGET): $(DEBUG_OBJS)
	mkdir -p $(TARGET_DIR)
	$(CXX) $(CXXFLAGS) $(DEBUG_OBJS) $(LIBS) -O0 -g -o $@

# removed $(DEBUG_OBJ_DIR) as it doesn't exists
clean:
	rm -rf $(OBJ_DIR) $(TARGET) $(DEBUG_TARGET)

# Include dependency files generated by the compiler. If a header changes,
# the corresponding .d file will make make rebuild the affected object.
-include $(OBJS:.o=.d)
-include $(DEBUG_OBJS:.o=.d)

