SRC_DIR=src
#SRCS=$(shell find $(SRC_DIR)/ -name *.cpp)
SRCS=src/asn1/asn1.cpp src/encryption/aes.cpp src/hash/sha.cpp src/pkcs/pkcs.cpp src/pkcs/private_key.cpp src/pkcs/public_key.cpp src/pkcs/sign.cpp src/tests/tests.cpp src/utils/base64.cpp src/utils/io.cpp src/main.cpp
TARGET_DIR=build/out
OBJ_DIR=build/obj
OBJS=$(SRCS:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%.o)
DEBUG_OBJS=$(SRCS:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%-debug.o)
TARGET=$(TARGET_DIR)/poc
DEBUG_TARGET=$(TARGET_DIR)/poc-debug
CXX=g++
DEPFLAGS=-MMD -MP
CXXFLAGS=-I$(SRC_DIR) -std=c++23
LIBS=-lgmp -lgmpxx -lcrypto

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(DEPFLAGS) -c $< -o $@

$(OBJ_DIR)/%-debug.o: $(SRC_DIR)/%.cpp
	mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(DEPFLAGS) -g -c $< -o $@

all: $(TARGET)

$(TARGET): $(OBJS)
	mkdir -p $(TARGET_DIR)
	$(CXX) $(CXXFLAGS) $(OBJS) $(LIBS) -O3 -o $@

debug: $(DEBUG_TARGET)

$(DEBUG_TARGET): $(DEBUG_OBJS)
	mkdir -p $(TARGET_DIR)
	$(CXX) $(CXXFLAGS) $(DEBUG_OBJS) $(LIBS) -g -o $@

clean:
	rm -rf $(OBJ_DIR) $(DEBUG_OBJ_DIR) $(TARGET) $(DEBUG_TARGET)

# Include dependency files generated by the compiler. If a header changes,
# the corresponding .d file will make make rebuild the affected object.
-include $(OBJS:.o=.d)
-include $(DEBUG_OBJS:.o=.d)
